test/loadtime/cmd/report/main.go
test/loadtime/report/report.go

…with a minimum window size of 1 sec.

Changed the way we measure TPS to take the highest moving average..

---

go.mod
go.sum

includes the fix for: https://github.com/dymensionxyz/cosmosclient/issues/13

updated cosmosclient version to include bugfix

---

block/manager.go

until a more graceful mechanism is implemented.

fix: Added panic as a temp fix for DA retry failure 

---

block/manager.go
da/celestia/celestia.go

---
For Author:
---
For Reviewer:
--- 

fix: changed Backoff delay to Fixed delay

---

block/manager.go
da/celestia/celestia.go

Reverts dymensionxyz/dymint#301

Revert "fix: changed Backoff delay to Fixed delay"

---

block/manager.go
da/celestia/celestia.go

---
For Author:
---
For Reviewer:
--- 
Originally opened by @mtsitrin

fix: dymint uses uncapped backoff delay for submitting batches

---

.github/pull_request_template.md
.golangci.yml
contrib/githooks/pre-commit-config.yaml

---
For Author:
---
For Reviewer:
--- 

fix: pre commit false negative on local machine

---

node/node_test.go
node/testutils.go
rpc/middleware/client.go
rpc/middleware/middleware_test.go
rpc/middleware/registry.go
rpc/middleware/status.go
rpc/rpc_test.go
rpc/server.go
rpc/sharedtypes/sharedtypes.go
rpc/testutils/testutils.go

---
For Author:
---
For Reviewer:
---

feat: propagate node health to RPC server response

---

cmd/dymint/commands/start.go
node/node.go
p2p/gossip.go
settlement/dymension/dymension.go

---
For Author:
---
For Reviewer:
---

fix: removed panic alert from graceful shutdown

---

block/manager.go
block/manager_test.go
da/celestia/celestia.go
da/celestia/celestia_test.go
da/celestia/mock/server.go
da/da.go
da/da_test.go
da/grpc/grpc.go
da/grpc/mockserv/mockserv.go
da/mock/mock.go
node/node.go

---
For Author:
---
For Reviewer:
---

feat: toggle node health status based on data batch submission status

---

settlement/dymension/dymension.go
settlement/dymension/dymension_test.go
settlement/settlement.go

---
For Author:
---
For Reviewer:
---

fix: dymint out of sync in case of missed hub state update event

---

config/defaults.go

---
For Author:
---
For Reviewer:
---

chore: reduced empty blocks and batch submission default values

---

block/manager.go
config/defaults.go

---
For Author:
---
For Reviewer:
---

Merge with main 

---

settlement/settlement_test.go

---
For Author:
---
For Reviewer:
---

fix: Fixed bug in test where we didn't wait for settlement client to stop

---

config/toml.go

---
For Author:
---
For Reviewer:
---

fix: fixed avail in toml

---

config/config.go
config/defaults.go
config/toml.go
node/node.go

---
For Author:
---
For Reviewer:
---

feat: Add Prometheus HTTP Metric Server for Enhanced Monitoring

---

config/toml.go
da/celestia/celestia.go
da/celestia/celestia_test.go
da/celestia/config.go
da/celestia/fees.go
da/da_test.go

---
For Author:
---
For Reviewer:
---

feat: celestia fee should be calculated dynamically

---

da/celestia/celestia.go
da/celestia/config.go

---
For Author:
---
For Reviewer:
---

feat: gas adjustmnet parsable for celestia config

---

da/celestia/celestia_test.go
da/utils.go

---
For Author:
---
For Reviewer:
---

fix: fixed bug where the unhealthy da event didn't stop block production

---

config/toml.go
da/celestia/celestia.go
da/celestia/config.go
da/celestia/fees.go
da/celestia/fees_test.go
settlement/dymension/dymension.go

---
For Author:
---
For Reviewer:
---

fix: fix gas adjustment parameter

---

block/manager.go
da/avail/avail.go
da/celestia/celestia.go
go.mod
go.sum
settlement/dymension/dymension.go

---
For Author:
---
For Reviewer:
---

fix: avail submission was stuck waiting for finalization

---

config/defaults.go

---
For Author:
---
For Reviewer:
---

chore: reduced max_batch_size_in_bytes to support Avail's limit

---

settlement/dymension/dymension.go
settlement/dymension/dymension_test.go

---
For Author:
---
For Reviewer:
---

fix: dynamic subscriber name to avoid possible subscriber collision

---

settlement/dymension/dymension.go
settlement/dymension/dymension_test.go

---
For Author:
---
For Reviewer:
---

chore: rebase from main 

---

config/config.go
config/toml.go

---
For Author:
---
For Reviewer:
---

fix: fixed configuration validation, to support empty_blocks=0s

---

block/manager.go
settlement/dymension/dymension.go

---
For Author:
---
For Reviewer:
---

fix: exponantial timeout when submitting to the hub

---

block/manager.go

---
For Author:
---
For Reviewer:
---

feat: try to append empty block at the end of each non-empty batch

---

Makefile
config/defaults.go
rpc/client/client.go
version/version.go

---
For Author:
---
For Reviewer:
---

fix: Display actual version in RPC status

---

block/produce.go
block/testutil.go
node/node.go
rpc/client/client.go

---
For Author:
---
For Reviewer:
---

chore: removed logging of events due to log bloat

---

block/synctarget.go
settlement/base.go
utils/events.go

---
For Author:
---
For Reviewer:
---

chore: added missing return statement when subscription cancled

---

go.mod
go.sum

---
For Author:
---
For Reviewer:
---

chore: update cosmosclient

---

block/manager_test.go
block/retriever.go
da/celestia/celestia.go
da/mock/mock.go
settlement/dymension/dymension.go

---
For Author:
---
For Reviewer:
---

fix: checking DA received batches

---

block/manager_test.go
block/retriever.go
da/avail/avail.go
da/celestia/celestia.go
da/celestia/celestia_test.go
da/da.go
da/da_test.go
da/errors.go
da/grpc/grpc.go
da/grpc/mockserv/mockserv.go
da/mock/mock.go
da/utils.go
settlement/settlement_test.go
testutil/mocks.go

---
For Author:
---
For Reviewer:
---

refactor: da error handling refactor

---

CONTRIBUTING.md

Corrected a misspelled word and double word usage.

chore: typo fixes

---

config/defaults.go

fix: changed Change default block time and batch submit time in dymint.toml as set in roller currently
ref: closes #502

chore: Change default block time and batch submit time in dymint.toml

---

da/avail/avail.go
da/celestia/celestia.go
da/da.go

---
For Author:
---
For Reviewer:
---

fix: wrong submitted dapath to dimension hub. client info missing #586

---

settlement/dymension/dymension.go

Error added in the log when failed to submitting batch
Closes #560 
---
For Author:
---
For Reviewer:
---

chore: add error log on submit batch error

---

block/retriever.go

---
For Author:
---
For Reviewer:
---

fix: skip trying to apply blocks from DA with mismatched heights.

---

go.mod
go.sum
settlement/dymension/dymension.go

---
Close #XXX
For Author:
---
For Reviewer:
---

fix(settlement): removed deprecated `IntermediateStateRoot` from BD before batch submission

---

rpc/client/client.go

---
Close #666 
For Author:
---
For Reviewer:
---

Remove occurrence of Tendermint

---

block/manager.go
block/produce.go
p2p/gossip.go
state/indexer/block/kv/kv.go

---
Close #XXX
For Author:
---
For Reviewer:
---

fix(code standards): use errors.Is in several places

---

cmd/dymint/commands/start.go

---
Close #665 
For Author:
---
For Reviewer:
---

Check if config.Genesis is provided on node start

---

block/produce.go
block/submit.go
cmd/dymint/commands/root.go
cmd/dymint/commands/start.go
da/avail/avail.go
node/node.go
p2p/validator.go
rpc/client/client.go
rpc/server.go
settlement/dymension/dymension.go
settlement/grpc/grpc.go
state/txindex/kv/kv.go
types/state.go

---
Close #XXX
For Author:
---
For Reviewer:
---

fix(code standards): remove several error strings

---

block/manager.go
block/submit.go
block/submit_test.go

---
Close https://github.com/dymensionxyz/dymint/issues/675
For Author:
---
For Reviewer:
---

fix(manager): use mutex instead of atomic batchInProcess

---

config/config.go
config/config_test.go

---
Close #664 
For Author:
---
For Reviewer:
---

Add missing config validation

---

block/produce.go

---
Close https://github.com/dymensionxyz/dymint/issues/654
For Author:
---
For Reviewer:
---

fix(block production): apply block before gossiping

---

mempool/v1/mempool.go

---
Close #XXX
For Author:
---
For Reviewer:
---

feat(mempool): add a sanity check

---

node/node.go
node/node_test.go
rpc/client/client_test.go

---
Close #655 
For Author:
---
For Reviewer:
---

fix(mempool): Initialize the mempool with the correct(current) block height

---

p2p/validator.go
p2p/validator_test.go

---
Close #661 
For Author:
---
For Reviewer:
---

fix(p2p): handle default mempool check tx error case

---

block/produce.go
block/submit.go

---
Close #XXX
For Author:
---
For Reviewer:
---

refactor: refactored `handleSubmissionTrigger`

---

block/manager.go

---
Close #XXX
For Author:
---
For Reviewer:
---

refactor(manager): remove unnecessary start event listener

---

go.mod
go.sum

---
Close #XXX
For Author:
---
For Reviewer:
---

build(deps): updated to cosmosclient with ethermint support (instead of evmos)

---

go.mod
go.sum

Setting the version to the one used by ethermint
---
Close #XXX
For Author:
---
For Reviewer:
---

build(deps): downgrade go-ethereum dependency to match ethermint

---

block/errors.go
block/manager_test.go
block/retriever.go
da/celestia/celestia.go
da/celestia/celestia_test.go
da/errors.go

---
Close #651 
For Author:
---
For Reviewer:
---

fix(da): check DA client type before trying to fetch batch

---

.github/workflows/changelog.yml
CHANGELOG.md

---
Close #XXX
For Author:
---
For Reviewer:
---

feat(ci): Add changelog workflow

---

CHANGELOG.md
da/celestia/celestia.go
da/celestia/config.go

---
Close https://github.com/dymensionxyz/dymint/issues/741
For Author:
---
For Reviewer:
---

fix(celestia): impl retry on submit

---

CHANGELOG.md
rpc/json/handler.go

---
Close #751 
For Author:
---
For Reviewer:
---

fix(rpc): nil panic in rpc/json/handler.go WriteError

---

CHANGELOG.md
block/manager.go
block/synctarget.go

---
Close https://github.com/dymensionxyz/dymint/issues/744
For Author:
---
For Reviewer:
---

fix(logs): make logs more readable in a couple places, fix race cond

---

CHANGELOG.md
rpc/json/ws.go

---
Close #XXX
For Author:
---
For Reviewer:
---

fix(logging): added reason for websocket closed debug msg

---

CHANGELOG.md
da/celestia/celestia.go

---
Close #XXX
For Author:
---
For Reviewer:
---

fix(code standards): renames error -> err in celestia

---

.github/workflows/changelog.yml
CHANGELOG.md

---
Close #XXX
For Author:
---
For Reviewer:
---

chore: remove skip ci

---

block/executor.go
block/executor_test.go
block/produce.go

---
Close #XXX
For Author:
---
For Reviewer:
---

feat(produce): limiting block size by maxBatchSize

---

CHANGELOG.md
block/manager.go

---
Close #786 
For Author:
---
For Reviewer:
---

fix: removing height condition for applying cached blocks from p2p

---

CHANGELOG.md
block/retriever.go

---
Close #XXX
For Author:
---
For Reviewer:
---

fix(manager): get fresh height in loop

---

config/flags.go
testutil/types.go

fix function names
For Author:
---
For Reviewer:
---

chore: fix function names

---

p2p/client.go

Header p2p gossiper has been removed from the code since it is actually unused.
---
Close #810 
For Author:
---
For Reviewer:
---

feat(p2p): header gossiper removed

---

block/manager.go
block/manager_test.go
block/produce.go
block/production_test.go
block/submit.go
block/submit_test.go

---
Close #XXX
For Author:
---
For Reviewer:
---

feat: block progress to support ibc should be managed by produceloop

---

block/submit.go

---
Close #XXX
For Author:
---
For Reviewer:
---

patch to mtsitrin/324: simplify create batch 

---

block/manager.go

---
Close #XXX
For Author:
---
For Reviewer:
---

fix(dead code): removes last submission time from manager

---

settlement/dymension/dymension.go

---
Close #XXX
For Author:
---
For Reviewer:
---

fix(hubclient): multiple events recieved of hub batch acceptance cause subscription to get cancelled

---

block/production_test.go
block/submit.go

replaces https://github.com/dymensionxyz/dymint/pull/832, https://github.com/dymensionxyz/dymint/pull/830

patch to mtsitrin/324: simplify block creation

---

block/synctarget.go
settlement/dymension/dymension.go
utils/event/funcs.go

Not a real fix, but it doesn't hurt in the mean time

fix(local pub sub): use error for subscription cancelled (instead of info)

---

da/celestia/celestia.go

---
Close #729 
For Author:
---
For Reviewer:
---

fix(da): celestia height not updated when syncing

---

block/manager.go

---
Close #XXX
For Author:
---
For Reviewer:
---

fix(code standards): remove a few lines in manager start

---

config/defaults.go
config/toml.go
settlement/config.go
settlement/dymension/dymension.go
settlement/dymension/dymension_test.go

---
Close #792 
For Author:
---
For Reviewer:
---

feat(settlement): expose hub retry params to config 

---

.golangci.yml
settlement/dymension/dymension.go

---
Close #XXX
For Author:
---
For Reviewer:
---

fix(linter): gofumpt and fix golangcilint config

---

block/gossip.go
p2p/client.go
p2p/validator.go

---
Close #800 
For Author:
---
For Reviewer:
---

feat(p2p): improving logs

---

da/avail/avail.go
da/celestia/celestia.go
da/da.go
da/grpc/grpc.go
da/grpc/mockserv/mockserv.go
da/local/local.go
indexers/blockindexer/kv/kv.go
indexers/txindex/kv/kv.go
node/node.go
settlement/grpc/mockserv/mockserv.go
settlement/local/local.go
store/badger.go
store/kv.go
store/prefix.go
store/pruning.go
store/store.go
store/storeIface.go
store/store_test.go
test/loadtime/cmd/report/main.go
testutil/mocks.go

---
Close #XXX
For Author:
---
For Reviewer:
---

fix(code standards): use kv naming in store where appropriate

---

.github/pull_request_template.md
.github/workflows/changelog.yml
CHANGELOG.md

---
Close #XXX
For Author:
---
For Reviewer:
---

Chore: Init changelog

---

block/gossip.go
settlement/grpc/grpc.go
settlement/local/local.go

fix some function names
For Author:
---
For Reviewer:
---

chore: fix some function names

---

CHANGELOG.md
rpc/json/ws.go

--
---
Close #892 
For Author:
---
For Reviewer:
---

fix(rpc): Websocket memory leak

---

settlement/dymension/dymension.go
settlement/dymension/types.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

patch for mtsitrin 884: use errors.Is

---

block/block.go

--
---
Close #916 
For Author:
---
For Reviewer:
---

feat(block): adding info log for block applied height in full-node

---

config/p2p.go
config/toml.go
p2p/client.go

--
---
Close #906 
For Author:
---
For Reviewer:
---

feat (p2p): add support for persistent peers 

---

types/block.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(doc): app hash corresponds to h-1

---

buf.gen.yaml

--
minor fix
For Author:
---
For Reviewer:
---

fix: update buf.gen.yaml

---

cmd/dymint/main.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

feat(debug): adds profile server

---

block/manager.go
block/produce.go
block/submit.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

patch for mtsitrin 954 multiple accumulateddata in case of submission latency

---

CHANGELOG.md
block/submit.go

--
---
Close #957 
For Author:
---
For Reviewer:
---

fix(manager): Add start height to Submit batch to SL log message

---

block/pruning.go

--
---
Close https://github.com/dymensionxyz/dymint/issues/956
For Author:
---
For Reviewer:
---

fix(prune): fix guard for sequencer

---

block/manager.go

--
---
Close https://github.com/dymensionxyz/dymint/issues/961
For Author:
---
For Reviewer:
---

fix(doc): remove misleading comment on last submitted height field

---

da/avail/avail.go
da/celestia/celestia.go
types/metrics.go

--
---
Close #983 
For Author:
---
For Reviewer:
---

feat(da): add metric for consecutive failed da submissions

---

da/celestia/celestia.go
da/celestia/config.go
da/celestia/config_test.go
go.mod

--
---
Close #984 
For Author:
---
For Reviewer:
---

feat(da): add default retry value for celestia

---

block/submit.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix: added log for batch creation

---

block/manager.go

(cherry picked from commit 7ee8303601cd2290137804e7fcab7adfdbf91c38)
--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(manager): unsubmitted bytes for batch calculation fix (#1019)

---

go.mod
go.sum

--
---
Close #1055 
For Author:
---
For Reviewer:
---

fix(da): celestia openrpc version update

---

go.mod
go.sum

--
---
Close #XXX
For Author:
---
For Reviewer:
---

updated cometbft version 

---

block/retriever.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

doc(apply block): docstring apply local block

---

block/block.go

…is commited
--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(manager): proposer must be updated in the state before the batch is commited

---

block/block.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(manager): removed redundant validation err check

---

go.mod

--
---
Close #1166 
For Author:
---
For Reviewer:
---

Bump go version to 1.23.1

---

block/manager.go
settlement/dymension/dymension.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(manager): fixed getting proposer to get for next height and not current one

---

.github/workflows/golangci_lint.yml

--
---
Close #XXX
For Author:
---
For Reviewer:
---

chore(ci): bump golangci-lint v1.60

---

types/serialization.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(state): storing last header hash in store

---

block/executor.go
types/serialization.go
types/serialization_test.go
utils/proto/converters.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix: consensus msgs serialization

---

mempool/v1/mempool.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

feat: added more info to rejected tx log

---

block/fork.go
block/manager.go
block/manager_test.go
block/modes.go
block/produce.go
block/production_test.go
block/pruning_test.go
block/sequencers.go
block/submit_test.go
rpc/client/client.go
testutil/types.go
version/version.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

tweaks fixes

---

config/defaults.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix: default max proof time should be 5s

---

.github/workflows/build_and_push_image.yml
Dockerfile

--
---
Close #XXX
For Author:
---
For Reviewer:
---

chore(ci): build and push image

---

settlement/grpc/grpc.go

--
---
Close #1308 
For Author:
---
For Reviewer:
---

fix(sl): grpc sl add missing batch info

---

.github/workflows/e2e-tests.yml

--
---
Close #XXX
For Author:
---
For Reviewer:
---

chore(ci): fix artifact path

---

config/config.go
config/toml.go
node/node.go
store/badger.go

--
---
Close https://github.com/dymensionxyz/dymint/issues/1143
For Author:
---
For Reviewer:
---

feat(db): expose badger num compactors to dymin toml

---

types/serialization.go

--
---
Close #1326 
For Author:
---
For Reviewer:
---

fix(header): fix next header hash for migrated rollapps

---

block/manager.go

--
---
Close #1339 
For Author:
---
For Reviewer:
---

fix(sync): only trigger syncing or validation on startup (err block source not found fix)

---

block/manager.go
types/serialization.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(header): fix next header hash for migrated rollapps (#1327) + validation issue (#1339)

---

.golangci.yml
config/toml.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

feat(da): added config defaults for supported da 

---

Dockerfile

--
---
Close #XXX
For Author:
---
For Reviewer:
---

chore: bump golang to 1.24.0-alpine3.21 in Dockerfile

---

rpc/client/client.go
rpc/client/clientq_test.go

--
---
Close https://github.com/dymensionxyz/dymint/issues/1379 (I hope..)
For Author:
---
For Reviewer:
---

fix(comet rpc): fix blockchain info range filter

---

da/celestia/celestia.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(celestia): use namespace from dapath instead of config for retrieving

---

block/block.go
block/slvalidator_test.go
mocks/github.com/dymensionxyz/dymint/store/mock_Store.go
store/pruning.go
store/pruning_test.go
store/store.go
store/storeIface.go
testutil/block.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(store): remove redundant store of drs and da params

---

da/da.go
da/registry/registry.go
da/registry/registry_test.go
da/walrus/client.go
da/walrus/client/client.go
da/walrus/client/schema_aggregator.json
da/walrus/client/schema_publisher.json
da/walrus/client_test.go
da/walrus/config.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

feat(DA): added Walrus DA

---

da/loadnetwork/loadnetwork.go
da/loadnetwork/loadnetwork_test.go
da/loadnetwork/rpc/ln_rpc_client.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

feat(da): add balance to load network client

---

da/aptos/client.go
da/aptos/client_test.go
da/sui/client.go
da/sui/client_test.go
da/sui/noop/Move.lock
da/walrus/client.go
da/walrus/client_test.go
da/walrus/config.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(DA): incorrect DA path format for Sui, Aptos, and Walrus

---

.golangci.yml
config/toml.go
da/celestia/client/headers.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(celestia): use tm mashal/ummarshal celestia headers (v1.4)

---

da/celestia/client/headers.go

This is to make celestia da client compatible with v0.25.3 with breaking changes in the headers API.
It basically replaces extender headers marshal/unmarshall from custom to tendermint.
--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(celestia): use tm mashal/ummarshal celestia headers

---

da/solana/Readme.md
da/solana/client.go
da/solana/config.go
go.mod
go.sum

--
---
Close #XXX
For Author:
---
For Reviewer:
---

feat(da): improvements on solana config and instructions

---

.github/workflows/golangci_lint.yml
.golangci.yml

--
---
Close #XXX
For Author:
---
For Reviewer:
---

chore: bring linter in line with dymension repo

---

go.mod
go.sum

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix: solana-go repo update

---

da/solana/Readme.md
da/solana/config.go

--
---
Close #XXX
For Author:
---
For Reviewer:
---

fix(da): set solana default program and readme fix
