dymensionxyz/dymint

- settlement/base.go
- settlement/mock/mock.go
- settlement/settlement_test.go
(cherry picked from commit 514f383ecfe293aea9fcf5c98d5b67ef4e72c0c3)
> fix: changed latestHeight to be updated on batch acceptance 

- go.mod
- go.sum
- rpc/json/handler.go
- rpc/json/service.go
- rpc/json/ws_test.go
The subscribe response returned to register clients using ws had 2 issues:
1. It wasn't json-rpc 2.0 compatible
2. The response body didn't match what clients (such as keplr) were expecting.
> fix:  bad format of rpc subscribe response 

- settlement/base.go
- settlement/dymension/dymension.go
- settlement/errors.go
- settlement/settlement_test.go
---
For Author:
---
For Reviewer:
--- 
> fix: returns descriptive error in case no sequencer registered on the hub

- block/manager.go
- block/manager_test.go
- cmd/dymint/commands/start.go
- config/config.go
- config/config_test.go
- config/defaults.go
- conv/addr.go
- conv/addr_test.go
- conv/config.go
- conv/config_test.go
- node/integration_test.go
- node/node.go
- node/node_test.go
- rpc/client/client_test.go
- rpc/json/service_test.go
- rpc/json/ws_test.go
- settlement/base.go
- settlement/config.go
- settlement/dymension/dymension.go
- settlement/dymension/dymension_test.go
- settlement/mock/mock.go
- settlement/registry/registry.go
- settlement/settlement.go
- settlement/settlement_test.go
- state/executor.go
- state/executor_test.go
- testutil/mocks.go
* Main change is the breaking of the SL config from raw json to an explicit struct.
* also changing the `namespaceID` to string so it will be easier to set in conf file
* renamed `settlement.LayerClient` to `settlement.LayerI` to indicate it's an interface
---
For Author:
---
For Reviewer:
---
> feat: refactor dymint config to support loading configuration from file

- block/manager.go
- block/manager_test.go
- mocks/settlement/hubclient.go
- node/integration_test.go
- node/node_test.go
- node/testutils.go
- rpc/client/client_test.go
- rpc/json/service_test.go
- settlement/base.go
- settlement/dymension/dymension.go
- settlement/dymension/dymension_test.go
- settlement/errors.go
- settlement/mock/mock.go
- settlement/settlement.go
- settlement/settlement_test.go
- testutil/mocks.go
- utils/events.go
This pr moves the batch submission to settlement layer logic from the manager to the settlement.
By that it allows us to encapsulate the logic and handle any possible failures.
The manager will only be notified upon submission success or health status changes. 
---
For Author:
---
For Reviewer:
---
> feat: toggle settlement health event upon settlement batch submission status

- state/txindex/kv/kv.go
---
For Author:
---
For Reviewer:
---
> fix: skipping nil txs in the search result

- block/manager.go
- store/store.go
- types/errors.go
This PR adds validation that the state loaded correctly on init.
The initial state is created from the genesis file.
Afterward, the state expected to be loaded from persistent storage
---
For Author:
---
For Reviewer:
---
> fix: distinguish between different errors of state loading

- config/defaults.go
- node/integration_test.go
- node/node.go
- rpc/client/client_test.go
- settlement/mock/mock.go
mock SL doesn't use keyring path from config
this allows us to set whenever keyring_dir for the sequencer as default
set defaults to be more clear and useful for local run
The default path for sequencer keys will be `rootDir/sequecner_keys`
---
For Author:
---
For Reviewer:
---
> feat: mock SL doesn't use keyring path from config. 

- rpc/client/client.go
- rpc/json/service.go
---
For Author:
---
For Reviewer:
---
> chore: added subscription limits check

- da/celestia/celestia.go
- da/celestia/config.go
- da/da_test.go
---
For Author:
---
For Reviewer:
---
> fix: fixed namespaceID parsing from toml

- block/manager.go
- state/executor.go
- testutil/types.go
---
For Author:
---
For Reviewer:
---
> fix: rollapp evm on devnet crashing with lastresulthash mismatch

- config/config.go
- settlement/dymension/dymension.go
---
For Author:
---
For Reviewer:
---
> fix: fixed parsing rollappID parameter

- block/manager.go
- block/manager_test.go
- block/production_test.go
- config/config.go
- config/config_test.go
- config/flags.go
- node/integration_test.go
- node/node_test.go
- node/testutils.go
- rpc/client/client_test.go
- rpc/json/service_test.go
- settlement/config.go
- settlement/dymension/dymension.go
- testutil/block.go
- testutil/types.go
---
For Author:
---
For Reviewer:
---
> feat: better enforcement on dymint flags

- block/manager.go
- da/celestia/celestia_test.go
- node/node_test.go
- settlement/base.go
- settlement/events.go
---
For Author:
---
For Reviewer:
---
> fix: possible race condition with small batches upon batch submission 

- da/celestia/celestia.go
- da/celestia/celestia_test.go
- da/celestia/config.go
- da/celestia/mock/server.go
- da/da_test.go
- go.mod
- go.sum
- mocks/da/celestia/cnc_client.go
---
For Author:
---
For Reviewer:
---
> fix: updated go-cnc to match celetia light node v0.11

- da/celestia/celestia.go
- go.mod
- go.sum
- settlement/dymension/dymension.go
---
For Author:
---
For Reviewer:
---
> fix: dymint out of sync with hub on tx submission timeout

- da/celestia/celestia_test.go
- da/celestia/mock/server.go
- da/da_test.go
- p2p/client_test.go
- settlement/dymension/dymension_test.go
- settlement/settlement_test.go
1. fixed bug in `da/celestia/mock/server.go`
2. removed the usage of `test.NewLogger(t)` as it's causes some racing errors (in case go routines exists and writes to log after the test is finished)
3. changed `t.Skip("TODO")` to continue in da tests
---
For Author:
---
For Reviewer:
---
> fix: fixed race condition in some DA tests

- block/produce.go
---
For Author:
---
For Reviewer:
---
> chore: halt production incase of production error

- proto/types/dymint/dymint.proto
- types/pb/dymint/dymint.pb.go
- types/tx.go
1. fix some typos in .proto
2. re run `make proto-gen` make sure consistency of generated files
```
@bodhi-crypo ➜ /workspaces/dymint (main) $ sudo make proto-gen
Generating Protobuf files..
./proto/gen.sh
Deleting contents of ./p2p/pb
Deleting contents of ./pb/pb
Deleting contents of ./test/pb
Deleting contents of ./types/pb
Copying generated proto files to ./p2p/pb
Copying generated proto files to ./pb/pb
cp: cannot stat './proto/pb/pb/*': No such file or directory
Copying generated proto files to ./test/pb
Copying generated proto files to ./types/pb
Deleting proto pb dir
```
---
For Author:
---
For Reviewer:
---
> chore: fix some typos && re-run make proto-gen

- block/manager_test.go
- block/testutil.go
- da/celestia/mock/server.go
- da/da_test.go
- da/grpc/mockserv/mockserv.go
- da/local/local.go
- da/registry/registry.go
- settlement/local/local.go
- settlement/registry/registry.go
- settlement/registry/registry_test.go
- settlement/settlement_test.go
- testutil/mocks.go
to avoid compatibility issues, I've left it as `"mock"` in the configuration files.
On the source code, the local hub and local da are now called `local` instead of `mock`.
---
Close #XXX
For Author:
---
For Reviewer:
---
> style: rename local hub settlement to local instead of mock

- block/manager.go
- rpc/client/client_test.go
---
This PR solves the issue running the RunInitChain func for botch sequencers and full-nodes to update the lastState, and starts syncing after that.
Close #643 
For Author:
---
For Reviewer:
---
> fix: full-node panics with app hash mismatch error when syncing

- da/celestia/celestia.go
---
This is a fix to log an error only when there is actually an error in the RetrieveBatches and CheckBatchAvailability funcs for the celestia da, since now the msg is always logged.
Close #644 
For Author:
---
For Reviewer:
---
> fix: celestia wrong error log for availability checks and retrievals

- node/integration_test.go
- node/node.go
- node/node_test.go
- node/testutils.go
- rpc/client/client_test.go
- rpc/json/service_test.go
Enforce settlement config rollapp id to be same as chain id from the rollapp genesis file
---
Close #640 
For Author:
---
For Reviewer:
---
> Enforce config rollapp id to be same as genesis chain id

- block/block.go
- block/produce.go
- node/node.go
- store/pruning.go
- store/pruning_test.go
- store/store.go
- store/store_test.go
- store/types.go
- testutil/mocks.go
---
Closes https://github.com/dymensionxyz/dymint/issues/684
For Author:
---
For Reviewer:
---
> fix(store): do not discard CAS fail errors

- block/manager.go
- block/retriever.go
This thing was useless, AFAIU
---
Close #XXX
For Author:
---
For Reviewer:
---
> fix(concurrency): remove unused sync cond

- p2p/validator.go
---
Close #XXX
For Author:
---
For Reviewer:
---
> doc(gossip): clearer tx validation explanation

- da/celestia/celestia.go
- da/celestia/celestia_test.go
This is a code refactor to avoid using namespace id param from configuration in full-nodes, since it is not relevant and it can lead to potential config issues, and the important is the namespace used by sequencer when posting batches.
---
Close #718 
For Author:
---
For Reviewer:
---
> fix(da): full-node get the da fetch configuration from hub and not config

- CHANGELOG.md
- block/block.go
- block/manager.go
P2P gossiping tries to validate blocks on reception. However, the validation fails if blocks are received unordered, dropping them, and being unable to sync using p2p for any block received after. This PR fixes the issue validating blocks in order, moving the validation call after caching them, and before applying, once all blocks are received and can be applied in order.
---
Close #722 
For Author:
---
For Reviewer:
---
> fix(p2p): validate block before applying and not before caching in p2p gossiping

- CHANGELOG.md
- block/manager.go
- block/submit.go
- gerr/doc.go
- gerr/errors.go
- settlement/dymension/cosmosclient.go
- settlement/dymension/cosmosclient_test.go
- settlement/dymension/dymension.go
- settlement/settlement.go
- testutil/block.go
Note: over time I intend to follow up this PR with more cleanups, and more usage of gerr packge
---
Close https://github.com/dymensionxyz/dymint/issues/725
For Author:
---
For Reviewer:
---
> fix(produce loop): handle unauthenticated error in settlement layer

- CHANGELOG.md
- da/da.go
---
Close #XXX
For Author:
---
For Reviewer:
---
> fix(da): fixed da path seperator and encoding issue.

- CHANGELOG.md
- da/da_test.go
Easy to see that the code is now fine, but it doesn't hurt to have a regression test
---
Close #XXX
For Author:
---
For Reviewer:
---
> test(encoding): adds a fuzz test for da path encoding

- CHANGELOG.md
- da/celestia/config.go
- utils/retry/backoff_test.go
---
Close https://github.com/dymensionxyz/dymint/issues/752
For Author:
---
For Reviewer:
---
> fix(celestia): use fixed delay in repeat attempts

- CHANGELOG.md
- block/manager.go
- block/manager_test.go
- block/retriever.go
- block/state.go
- block/submit.go
- block/synctarget.go
- da/celestia/celestia.go
- da/celestia/config.go
- types/serialization.go
- types/state.go
- utils/event/funcs.go
- utils/retry/backoff_test.go
---
Close #771 , https://github.com/dymensionxyz/dymint/issues/761
For Author:
---
For Reviewer:
---
> fix(bug): sync from da and p2p when starting a node

- block/manager.go
- block/manager_test.go
- config/defaults.go
- node/node.go
- p2p/client.go
- p2p/client_test.go
- p2p/gossip.go
- p2p/validator.go
- p2p/validator_test.go
- testutil/block.go
- testutil/p2p.go
This PR decouples p2p gossip blocks validation from blocks reception. By doing that we avoid any interference of block store application in block propagation.
---
Close #802 
For Author:
---
For Reviewer:
---
> feat(p2p): moving gossiped blocks reception from validator to p2p client

- block/produce.go
- block/production_test.go
---
Close #XXX
For Author:
---
For Reviewer:
---
> patch to mtsitrin/324: simplify empty timing

- settlement/dymension/dymension.go
---
Close #XXX
For Author:
---
For Reviewer:
---
> fix(submission): Added another loop to not revert to submission while waiting for batch

- block/retriever.go
This PR removes the availability checks from the retriever, since it requires additional syncing with DA and availability checks are not really necessary at this point where sequencers are trusted and fraud proofs are not enabled yet in full-nodes.
---
Close #834 
For Author:
---
For Reviewer:
---
> feat(p2p): remove availability checks from retriever

- settlement/dymension/dymension.go
- settlement/dymension/dymension_test.go
---
Close #844 
For Author:
---
For Reviewer:
---
> fix(settlement): filter by pending status in batch event

- node/node.go
---
this change passes the received metrics provider from function arguments down to dymint mempool creation. after enabling this, mempool size metric is available on the `/metrics` endpoint. Other metrics will come in a separate PR.
```
❯ curl localhost:2112/metrics | grep dymint
dymint_mempool_size 0
```
For Author:
---
For Reviewer:
---
> fix(metrics): pass metrics to mempool init

- .github/workflows/changelog.yml
---
This PR add auto changelog workflow as the following:
When new commit pushed/PR merged to main branch then
Check if a changelog PR already opened:
- (Yes) merge from main branch (with ort strag) if needed, then new changelog entry will be append to changelog.md and update to already open PR then exit.
- (No) checkout from main branch, generate changelog entry and create PR.
Branch should delete automatically on next ci run, or you can delete it manully.
**NOTE**
Do not create branch "auto-changelog-update-do-not-create-manually" manually.
For Author:
---
For Reviewer:
---
> feat(ci): new changelog workflow

- block/submit.go
---
Close #XXX
For Author:
---
For Reviewer:
---
> fix(docs): make submit loop comment more accurate re batch size

- .github/workflows/golangci_lint.yml
- .golangci.yml
- block/manager.go
- block/synctarget.go
- p2p/client.go
- p2p/validator_test.go
- rpc/client/client.go
- rpc/json/handler.go
- rpc/server.go
- settlement/base.go
- settlement/events.go
- test/loadtime/cmd/report/main.go
- types/validation.go
---
Close #XXX
For Author:
---
For Reviewer:
---
> fix(code standards): bring over more linters and the github integration from hub repo

- block/manager.go
- block/produce.go
- block/submit.go
- da/celestia/celestia.go
- settlement/dymension/dymension.go
---
Close #801 
For Author:
---
For Reviewer:
---
> feat(da): improve logging

- block/block.go
- block/executor_test.go
- block/state.go
> fix(code standards): inline NextValSetFromResponses

- config/toml.go
- settlement/config.go
- settlement/dymension/dymension.go
---
Close #493 
For Author:
---
For Reviewer:
---
> chore(config): better naming for settlement config

- rpc/middleware/middleware_test.go
- rpc/middleware/status.go
---
Close #XXX
For Author:
---
For Reviewer:
---
> fix: remove unnecessary `:` in the json response

- block/manager.go
- block/retriever.go
- da/avail/avail.go
- da/celestia/celestia.go
- da/da.go
- da/grpc/grpc.go
- da/local/local.go
The main objective of this PR is the startup process for Celestia DA for full-nodes. With the modifications, full nodes will not wait for a DA to be in sync (or up) and it will do the syncing process in the background, while the full-node can start receiving and caching gossiped blocks from P2P. It also solves  a nil pointer error that was happening when DA light finished syncing and a full-node was started when was not still in sync. Without the modifications of this PR, a node could start receiving gossiped blocks, but everything received while DA was syncing was disregarded because the block manager was not started, waiting for the celestia light node to finish the syncing process.
---
Close #856 , #799 , https://github.com/dymensionxyz/dymint/issues/770
<-- Briefly describe the …
> fix(da): full-nodes can sync from p2p while DA light client is down or out of sync

- block/produce.go
- indexers/blockindexer/kv/kv.go
- store/badger.go
- store/badger_test.go
- store/store_test.go
uses a standard err definition instead of a bespoke one
> fix(code standards): use gerr err not found

- block/executor.go
- block/produce.go
- block/submit_test.go
- block/types.go
- config/config_test.go
- testutil/types.go
- types/batch.go
--
---
Close #885 
For Author:
---
For Reviewer:
---
> fix(block manage): reducing batch overhead size when reaping Txs from mempool

- config/toml.go
- da/celestia/celestia.go
This PR removes the retry function from the DA submission loop, since it delays the submission error and it can lead to confusion when checking the logs without adding anything. It will be retried anyway in an endless loop till it succeeds.
--
---
Close #919 
For Author:
---
For Reviewer:
---
> fix(da): submission retry function removed

- CHANGELOG.md
- block/retriever.go
--
---
Close #917 
For Author:
---
For Reviewer:
---
> fix(code standards): remove misleading part of log message upon app hash mismatch

- block/manager.go
- block/produce.go
- block/production_test.go
- block/submit.go
- block/submit_test.go
> fix(blockManager): multiple accumulateddata trigger

- block/retriever.go
--
---
Close https://github.com/dymensionxyz/dymint/issues/955
For Author:
---
For Reviewer:
---
> fix(sync): adds missing error log

- config/config.go
- settlement/settlement.go
fix some comments for struct field
For Author:
---
For Reviewer:
---
> chore(code standards): fix some comments for struct field

- CHANGELOG.md
- block/manager.go
- block/manager_test.go
- block/produce.go
- block/production_test.go
- block/state.go
- block/submit.go
- block/submit_loop_test.go
- block/submit_test.go
- da/local/local.go
- settlement/dymension/dymension.go
- types/batch.go
- types/block.go
- types/metrics.go
- utils/channel/funcs.go
- utils/event/funcs.go
--
---
Close https://github.com/dymensionxyz/dymint/issues/963, https://github.com/dymensionxyz/dymint/issues/968, https://github.com/dymensionxyz/dymint/issues/973
For Author:
---
For Reviewer:
---
> fix(submission): fix counting and time

- block/retriever.go
--
---
Close #1033 
This PR fixes a bug that causes the retrieve mutex is not unlocked if it fails to apply local block stored in db, which will happen in case the block is already applied  between the time the block is loaded from db and its applied. 
For Author:
---
For Reviewer:
---
> fix(manager): applylocalblock change mutex

- rpc/json/ws.go
In case RPC websocket is closed with an error that is not websocket.CloseError, UnsubscribeAll is not called. This causes the service may try to write to a closed channel, when the error happens and the websocket is closed. 
This PR basically calls UnsubscribeAll when any error
---
Close #1043 
For Author:
---
For Reviewer:
---
> fix(rpc): fix websocket subscription panic when no closing error

- block/block.go
- block/manager.go
- block/pruning.go
- block/pruning_test.go
- block/submit.go
- p2p/client.go
- store/pruning.go
- store/pruning_test.go
- store/store.go
- store/storeIface.go
In case there is some height with a key missing in the store, or in case pruning fails at a specific height for some reason, the pruning returns error.
In this PR this logic is changed and the pruning continues for other heights.
--
---
Close #1039 
For Author:
---
For Reviewer:
---
> fix(store): improve pruning to avoid skipped heights

- settlement/dymension/dymension.go
This PR implements https://www.notion.so/dymension/DRS-Vulnerability-Recovery-5b42195818264165aa72718e0e173f5b
Closes https://github.com/dymensionxyz/dymension/issues/1207
---
For Author:
---
For Reviewer:
---
> feat(settlement): added DRS version to MsgUpdateState

- block/initchain.go
- block/sequencers.go
- block/state.go
- rpc/client/client.go
- rpc/client/client_test.go
- testutil/types.go
- types/sequencer_set.go
I guess it should work, I haven't e2e tested it
--
---
Close #https://github.com/dymensionxyz/dymint/issues/1134
For Author:
---
For Reviewer:
---
> fix(validator set): use comet compatible API for validators set wrt hash

- block/manager.go
- block/pruning.go
- block/validate.go
- rpc/client/client.go
- rpc/client/client_test.go
- rpc/json/service.go
--
---
Close #1128
For Author:
---
For Reviewer:
---
> feat(rpc): new endpoint for block validation status

- block/manager_test.go
- block/retriever.go
- block/slvalidator_test.go
- block/sync.go
--
---
Close #1169 
For Author:
---
For Reviewer:
---
> fix(settlement): use block descriptors as source of truth for blocks to apply 

- rpc/client/client.go
- rpc/client/client_test.go
- rpc/json/service.go
--
---
Close #XXX
For Author:
---
For Reviewer:
---
> feat: add chainID to `BlockValidated` rpc

- block/block.go
- block/initchain.go
- block/manager.go
- block/modes.go
- block/produce.go
- block/pruning.go
- block/sequencers.go
- block/state.go
- mocks/github.com/dymensionxyz/dymint/settlement/mock_ClientI.go
- settlement/dymension/dymension.go
- settlement/grpc/grpc.go
- settlement/local/local.go
- settlement/settlement.go
--
---
Close #XXX
For Author:
---
For Reviewer:
---
> refactor(manager): cleanup proposer, full node and rotation flows

- block/validate.go
In the validation loop, it may fail to validate because it tries to validate to heights for blocks that are not applied yet. 
This PR fixes this by never validating heights that are not applied yet. 
--
---
Close #1186 
For Author:
---
For Reviewer:
---
> fix(validation): set right validation height

- settlement/dymension/dymension.go
--
---
Close #1197 
For Author:
---
For Reviewer:
---
> fix(sl): when getting proposer per height get all sequencers and not just bonded

- block/block.go
- block/fraud.go
- block/manager.go
- block/manager_test.go
- block/modes.go
- block/p2p.go
- block/retriever.go
- block/sync.go
--
---
Close #XXX
For Author:
---
For Reviewer:
---
> feat(manager): stop applying blocks after node set unhealthy

- .golangci.yml
- block/submit.go
Linter CI is failing with multiple "G115: integer overflow conversion" errors. All these errors are false positives; conversions were done intentionally, and there is no way to fix them (or there are, but hardly feasible). Adding `//nolint:gosec` everywhere is annoying, so I decided to exclude the G115 error from linter. 
For example:
```
2024-11-11T19:31:33.8301723Z ##[error]block/executor.go:317:19: G115: integer overflow conversion int -> uint32 (gosec)
2024-11-11T19:31:33.8311382Z 				Index:  uint32(i),
2024-11-11T19:31:33.8312034Z 				              ^
2024-11-11T19:31:33.8313738Z ##[error]block/fork.go:164:19: G115: integer overflow conversion uint64 -> uint32 (gosec)
2024-11-11T19:31:33.8315742Z 		if drs == uint32(actualDRS) {
2024-11-11T19:31:33.8316405Z 		                ^ …
```
> chore: added integer overflow linter error to exclude list

- block/manager_test.go
- block/retriever.go
- block/slvalidator.go
- block/slvalidator_test.go
- block/validate.go
- settlement/settlement.go
- testutil/block.go
- testutil/types.go
- types/errors.go
refactored nextSequencer validation
--
---
Close #XXX
For Author:
---
For Reviewer:
---
> fix(validation): added da batch validation against state BD desc

- block/fork.go
- block/fork_test.go
- types/rollapp_test.go
--
---
Close #XXX
For Author:
---
For Reviewer:
---
> fix: get revision for height instead of the latest

- block/produce.go
List of corner cases: https://www.notion.so/dymension/UpsertSequencer-consensus-msg-corner-cases-150a4a51f86a800caaa3fcd8d3a33adb?pvs=4
| Scenario                                                                                                 | Reboot | In-memory set | Store set  | Rollapp state | Produce next empty block                                                                                               |
|----------------------------------------------------------------------------------------------------------|--------|---------------|------------|---------------|------------------------------------------------------------------------------------------------------------------------|
| Fail before SnapshotSequencerSet …
> feat: produce empty blocks if there are any sequencer set updates

- block/fork.go
- block/fork_test.go
- block/manager.go
- block/modes.go
- block/production_test.go
- block/submit_test.go
- types/instruction.go
The objective of this PR is to fix detected issues in forking process:
* Stop condition modified to avoid stopping active proposers when submitting fork batch is wrong, rolled back to previous and added mutex.
* fork for deprecated drs for rollapps with multiple forks did not work because instruction file could have info from wrong fork (for previous height and not next height). its been fixed by getting always fork data from hub using current height.     
--
---
Close #1268, #1267 
For Author:
---
For Reviewer:
---
> fix(fork): drs upgrade when multiple forks fix

- block/fork.go
- block/manager.go
- types/state.go
This PR goes with with https://github.com/dymensionxyz/rollapp-evm/pull/393
where drs rollapp param validation is moved to the begin blocker function to be aligned with upgrade flow, otherwise its not possible to run a new version (it will fail in dymint validation) before the drs is updated in the upgrade handler. 
--
---
Close #1271 
For Author:
---
For Reviewer:
---
> feat(upgrade): move drs check to begin blocker to allow time-based upgrades

- block/fork.go
--
---
Close #XXX
For Author:
---
For Reviewer:
---
> feat(drs): only send consensus msgs for drs upgrade when necessary

- block/block.go
- block/manager.go
- block/produce.go
- block/pruning.go
- block/submit.go
- block/submit_loop_test.go
- block/submit_test.go
- block/sync.go
- settlement/dymension/utils.go
- settlement/local/local.go
- settlement/settlement.go
This PR solves two issues:
- submission time when no state update is submitted should take first block as a reference, and no the genesis time (to calculate skew time).
- batch_submission_time (config) should be based on submissions time, and no based on block times, otherwise it maybe that the submissions are not exactly every batch_submission_time when no block production. 
Close #1282 ,#1287
For Author:
---
For Reviewer:
---
> max skew time + batch submission time calculation refactor

- block/fork.go
- block/slvalidator.go
- to avoid false positive state validation when multiple forks, because its not skipping next sequencer validation in the previous state update to a fork 
--
---
Close #1297 
For Author:
---
For Reviewer:
---
> fix(fork): get next revision start height from sl in validation 

- .github/workflows/e2e-tests.yml
--
---
Close #XXX
For Author:
---
For Reviewer:
---
> chore(ci): add workflow for e2e-tests

- block/manager.go
- mocks/github.com/dymensionxyz/dymint/p2p/mock_StateGetter.go
- p2p/block_sync_test.go
- p2p/client.go
- p2p/client_test.go
- p2p/gossip.go
- p2p/validator.go
- p2p/validator_test.go
- types/state.go
--
---
Closes https://github.com/dymensionxyz/dymint/issues/1240
Closes https://github.com/dymensionxyz/dymint/issues/1311
For Author:
---
For Reviewer:
---
> fix(validation): fix nil deref , and use validation result

- block/executor.go
- block/executor_test.go
- rpc/client/client.go
- testutil/types.go
- types/block.go
- types/conv.go
--
---
Closes https://github.com/dymensionxyz/research/issues/449
For Author:
---
For Reviewer:
---
> fix(abci): use correct hash in abci block.LastCommit.BlockID

- da/avail/avail.go
--
---
Close #XXX
For Author:
---
For Reviewer:
---
> fix(avail): ignoring in case of garbage data on the avail DA

- store/prefix_test.go
Corrected "preffix" to "prefix" in the comments.
> Fix typo prefix_test.go

- block/sequencers_test.go
This pull request fixes a typo in the `sequencers_test.go` file. The word **"manger"** has been corrected to **"manager"**.
- Corrected the typo **"manger"** to **"manager"** in the `TestHandleSequencerSetUpdate` test function.
- The typo could lead to confusion and affect the readability of the test code.
- Correcting this typo helps maintain consistency and clarity in the codebase.
- Review the `sequencers_test.go` file to confirm the typo has been fixed.
- Run the test suite to ensure the test still works correctly after the change.
- This is a minor correction and does not affect any functionality of the codebase.
> sequencers_test.go

- rpc/json/ws_test.go
This pull request corrects a typo in the `ws_test.go` file. The word **"Vaildate"** has been fixed to **"Validate"** to ensure accuracy in the comment.
- Corrected the typo in the comment:
- **Before:** `// Vaildate we have a new client`
- **After:** `// Validate we have a new client`
- This is a non-functional change that only affects comments, improving the clarity of the code.
- No testing is required since this is only a comment fix.
> fix typo ws_test.go

- indexers/txindex/kv/kv_bench_test.go
- indexers/txindex/kv/kv_test.go
- settlement/local/local_test.go
- store/store_test.go
--
---
Close #XXX
`TempDir()` is a method introduced in Go 1.15 for `testing.T`. It automatically creates a temporary directory and cleans it up after the test is complete, eliminating the hassle of manually handling errors and cleanup.  More detail about TempDir  https://pkg.go.dev/testing#B.TempDir
For Author:
---
For Reviewer:
---
> refactor: use t.TempDir() instead of os.MkdirTemp

- config/defaults.go
- settlement/dymension/dymension.go
this pr removes the skip retry because unrecoverable when state info not found, because it could happen if hub node is behind load balancer and are not perfectly synced. with the change it will retry using default values to avoid freezing when small syncing issues on the hub.
--
---
Close #XXX
For Author:
---
For Reviewer:
---
> fix(validation): remove unrecoverable when state info not found 
